# Generated by Django 2.2.6 on 2019-10-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0002_album_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='myfile',
            new_name='myfiles',
        ),
    ]
